app.moveData = {
	megahorn:           {
		name:          "Megahorn",
		type:          "Bug",
		stoneOptions:  "110000",
		ingameDesc:    "Using its tough and impressive horn, the user rams into enemies in front of itself with no letup, dealing huge damage to them.",
		tierlistRank:  "S-",
		power:         513,
		cooldown:      5,
	},
	uturn:              {
		name:          "U-turn",
		type:          "Bug",
		stoneOptions:  "110100",
		ingameDesc:    "After attacking surrounding enemies, the user moves back to dodge enemies' counterattacks.",
		tierlistRank:  "B",
		power:         243,
		cooldown:      5,
	},
	leechlife:          {
		name:          "Leech Life",
		type:          "Bug",
		stoneOptions:  "111000",
		ingameDesc:    "The user drains the blood of enemies directly in front of itself, damaging them. Part of the damage dealt is absorbed to restore the user's HP.",
		tierlistRank:  "C",
		power:         185,
		cooldown:      9,
	},
	lunge:              {
		name:          "Lunge",
		type:          "Bug",
		stoneOptions:  "111000",
		ingameDesc:    "The user lunges toward enemies in front of itself, damaging them.",
		tierlistRank:  "B",
		power:         180,
		cooldown:      5,
	},
	stringshot:         {
		name:          "String Shot",
		type:          "Bug",
		stoneOptions:  "110101",
		ingameDesc:    "The user spews a sticky thread in three directions, creating nets that will damage enemies and often lower their movement speed.",
		tierlistRank:  "C",
		power:         118,
		cooldown:      2,
	},
	silverwind:         {
		name:          "Silver Wind",
		type:          "Bug",
		stoneOptions:  "111111",
		ingameDesc:    "Scales carried by the wind swirl around the user, damaging enemies hit by them. Some or all of the user's stats sometimes rise at random.",
		tierlistRank:  "C",
		power:         53,
		cooldown:      5,
	},
	ragepowder:         {
		name:          "Rage Powder",
		type:          "Bug",
		stoneOptions:  "110000",
		ingameDesc:    "The user scatters a cloud of irritating powder on itself, causing surrounding enemies to target it.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      2,
	},
	pinmissile:         {
		name:          "Pin Missile",
		type:          "Bug",
		stoneOptions:  "111100",
		ingameDesc:    "The user shoots three sharp spikes in front of itself, damaging enemies hit by them.",
		tierlistRank:  "B",
		power:         110,
		cooldown:      7,
	},
	crunch:             {
		name:          "Crunch",
		type:          "Dark",
		stoneOptions:  "111000",
		ingameDesc:    "The user takes aim and then bites on to enemies a short distance in front of itself, damaging them.",
		tierlistRank:  "B",
		power:         370,
		cooldown:      5,
	},
	suckerpunch:        {
		name:          "Sucker Punch",
		type:          "Dark",
		stoneOptions:  "110000",
		ingameDesc:    "The user briefly disappears and moves a short distance. It then charges toward enemies, damaging them.",
		tierlistRank:  "C",
		power:         130,
		cooldown:      5,
	},
	nightslash:         {
		name:          "Night Slash",
		type:          "Dark",
		stoneOptions:  "111000",
		ingameDesc:    "The user dashes forward, slashing surrounding enemies and damaging them. Critical hits land more easily.",
		tierlistRank:  "C",
		power:         83,
		cooldown:      5,
	},
	taunt:              {
		name:          "Taunt",
		type:          "Dark",
		stoneOptions:  "110000",
		ingameDesc:    "The user taunts surrounding enemies, forcing them to target it.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      2,
	},
	nastyplot:          {
		name:          "Nasty Plot",
		type:          "Dark",
		stoneOptions:  "110011",
		ingameDesc:    "The user stimulates its brain by thinking bad thoughts, raising the amount of damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      0,
	},
	flatter:            {
		name:          "Flatter",
		type:          "Dark",
		stoneOptions:  "110001",
		ingameDesc:    "The user flatters enemies in front of itself, which confuses them but raises the amount of damage they deal and reduces the amount of damage they take.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      6,
	},
	dracometeor:        {
		name:          "Draco Meteor",
		type:          "Dragon",
		stoneOptions:  "110000",
		ingameDesc:    "The user summons several meteors down around itself, damaging enemies hit by them. Sometimes reduces the amount of damage the user deals.",
		tierlistRank:  "A",
		power:         377,
		cooldown:      5,
	},
	dragonclaw:         {
		name:          "Dragon Claw",
		type:          "Dragon",
		stoneOptions:  "111000",
		ingameDesc:    "The user gathers its strength, then charges forward while spinning, damaging enemies with its sharp claws.",
		tierlistRank:  "B",
		power:         296,
		cooldown:      5,
	},
	dragonrush:         {
		name:          "Dragon Rush",
		type:          "Dragon",
		stoneOptions:  "110100",
		ingameDesc:    "The user flies into enemies a short distance from itself with great intensity, damaging them.",
		tierlistRank:  "B-",
		power:         141,
		cooldown:      5,
	},
	twister:            {
		name:          "Twister",
		type:          "Dragon",
		stoneOptions:  "111100",
		ingameDesc:    "The user whips up several tornadoes and sends them out in front of itself, damaging enemies hit by them.",
		tierlistRank:  "B-",
		power:         115,
		cooldown:      7,
	},
	outrage:            {
		name:          "Outrage",
		type:          "Dragon",
		stoneOptions:  "111000",
		ingameDesc:    "The user rampages about, attacking and damaging any enemies in its path. Sometimes confuses the user.",
		tierlistRank:  "C",
		power:         104,
		cooldown:      5,
	},
	dragondance:        {
		name:          "Dragon Dance",
		type:          "Dragon",
		stoneOptions:  "110000",
		ingameDesc:    "The user vigorously performs a mystic, powerful dance that raises the amount of damage it deals and its movement speed for a while.",
		tierlistRank:  "A-",
		power:         0,
		cooldown:      8,
	},
	dragonpulse:        {
		name:          "Dragon Pulse",
		type:          "Dragon",
		stoneOptions:  "111100",
		ingameDesc:    "The user sends a shock wave flying from its mouth, damaging enemies hit by it.",
		tierlistRank:  "B-",
		power:         188,
		cooldown:      7,
	},
	thunder:            {
		name:          "Thunder",
		type:          "Electric",
		stoneOptions:  "110000",
		ingameDesc:    "The user strikes the area in front of itself with a lightning bolt. Deals damage to nearby enemies. Sometimes paralyzes enemies.",
		tierlistRank:  "A",
		power:         204,
		cooldown:      5,
	},
	thunderpunch:       {
		name:          "Thunder Punch",
		type:          "Electric",
		stoneOptions:  "111001",
		ingameDesc:    "The user charges its fist with electricity and unleashes a shocking punch on enemies directly in front of itself, sometimes paralyzing them.",
		tierlistRank:  "B",
		power:         194,
		cooldown:      5,
	},
	thundershock:       {
		name:          "Thunder Shock",
		type:          "Electric",
		stoneOptions:  "110101",
		ingameDesc:    "After storing up electricity, the user fires it toward enemies in front of itself, dealing damage to them. Sometimes paralyzes enemies.",
		tierlistRank:  "B",
		power:         173,
		cooldown:      5,
	},
	volttackle:         {
		name:          "Volt Tackle",
		type:          "Electric",
		stoneOptions:  "110001",
		ingameDesc:    "After electrifying itself and charging toward enemies, the user jumps and discharges electricity, damaging enemies hit by it and sometimes paralyzing them.",
		tierlistRank:  "B-",
		power:         110,
		cooldown:      6,
	},
	spark:              {
		name:          "Spark",
		type:          "Electric",
		stoneOptions:  "110001",
		ingameDesc:    "The user charges its body with electricity and charges toward enemies in front of itself. Sometimes paralyzes enemies.",
		tierlistRank:  "B-",
		power:         81,
		cooldown:      5,
	},
	thunderbolt:        {
		name:          "Thunderbolt",
		type:          "Electric",
		stoneOptions:  "110101",
		ingameDesc:    "The user discharges tremendous electricity all around itself. Deals damage to enemies around the user. Sometimes paralyzes enemies.",
		tierlistRank:  "B-",
		power:         80,
		cooldown:      5,
	},
	electricterrain:    {
		name:          "Electric Terrain",
		type:          "Electric",
		stoneOptions:  "110011",
		ingameDesc:    "The user gathers electrical power beneath itself, raising the damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	electroweb:         {
		name:          "Electroweb",
		type:          "Electric",
		stoneOptions:  "111101",
		ingameDesc:    "The user spreads an electric net out directly in front of itself, lowering the movement speed of enemies hit by it for a while.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	charge:             {
		name:          "Charge",
		type:          "Electric",
		stoneOptions:  "110011",
		ingameDesc:    "The user stores up electricity, raising the damage it deals and making it resistant to negative effects for a while.",
		tierlistRank:  "A",
		power:         0,
		cooldown:      9,
	},
	dazzlinggleam:      {
		name:          "Dazzling Gleam",
		type:          "Fairy",
		stoneOptions:  "110000",
		ingameDesc:    "The user moves about as it emits a powerful flash that damages enemies hit by it.",
		tierlistRank:  "B-",
		power:         146,
		cooldown:      5,
	},
	playrough:          {
		name:          "Play Rough",
		type:          "Fairy",
		stoneOptions:  "110001",
		ingameDesc:    "The user plays rough with enemies in front of itself, damaging them. Sometimes lowers the damage enemies deal.",
		tierlistRank:  "C",
		power:         98,
		cooldown:      5,
	},
	charm:              {
		name:          "Charm",
		type:          "Fairy",
		stoneOptions:  "110001",
		ingameDesc:    "The user makes surrounding enemies less wary with its cute behavior, often reducing the amount of damage they deal.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      3,
	},
	drainingkiss:       {
		name:          "Draining Kiss",
		type:          "Fairy",
		stoneOptions:  "111000",
		ingameDesc:    "The user kisses enemies directly in front of itself and damages them. Part of the damage dealt restores the user's HP.",
		tierlistRank:  "C",
		power:         165,
		cooldown:      9,
	},
	sweetkiss:          {
		name:          "Sweet Kiss",
		type:          "Fairy",
		stoneOptions:  "111001",
		ingameDesc:    "The user kisses enemies directly in front of itself with a sweet, angelic kiss that often confuses them.",
		tierlistRank:  "B-",
		power:         165,
		cooldown:      3,
	},
	highjumpkick:       {
		name:          "High Jump Kick",
		type:          "Fighting",
		stoneOptions:  "110000",
		ingameDesc:    "After charging toward enemies in front of itself, the user jumps up and deals damage with a knee kick. The user also takes recoil damage.",
		tierlistRank:  "B-",
		power:         402,
		cooldown:      5,
	},
	crosschop:          {
		name:          "Cross Chop",
		type:          "Fighting",
		stoneOptions:  "110000",
		ingameDesc:    "The user jumps toward enemies in front of itself and smacks them with a two handed chop, damaging them. Critical hits land more easily.",
		tierlistRank:  "B",
		power:         273,
		cooldown:      5,
	},
	closecombat:        {
		name:          "Close Combat",
		type:          "Fighting",
		stoneOptions:  "110100",
		ingameDesc:    "The user gets right up on enemies in front of itself and smacks them with a single blow, damaging them. Sometimes raises the amount of damage the user takes.",
		tierlistRank:  "S+/A-",
		power:         245,
		cooldown:      5,
	},
	drainpunch:         {
		name:          "Drain Punch",
		type:          "Fighting",
		stoneOptions:  "111000",
		ingameDesc:    "The user fires a punch at enemies directly in front of itself, damaging them. It also absorbs power with its fist, restoring its own HP.",
		tierlistRank:  "C",
		power:         223,
		cooldown:      9,
	},
	rollingkick:        {
		name:          "Rolling Kick",
		type:          "Fighting",
		stoneOptions:  "110100",
		ingameDesc:    "The user kicks as it spins in place, dealing damage to surrounding enemies.",
		tierlistRank:  "B-",
		power:         156,
		cooldown:      5,
	},
	submission:         {
		name:          "Submission",
		type:          "Fighting",
		stoneOptions:  "110000",
		ingameDesc:    "The user spins toward enemies in front of itself, smashing into them. Deals damage to enemies hit by the user as it whirls around.",
		tierlistRank:  "C",
		power:         130,
		cooldown:      5,
	},
	dynamicpunch:       {
		name:          "Dynamic Punch",
		type:          "Fighting",
		stoneOptions:  "111001",
		ingameDesc:    "The user punches enemies directly in front of itself with its full, concentrated power. Sometimes confuses enemies.",
		tierlistRank:  "C",
		power:         87,
		cooldown:      5,
	},
	poweruppunch:       {
		name:          "Power-Up Punch",
		type:          "Fighting",
		stoneOptions:  "110000",
		ingameDesc:    "The user delivers a punch with its hard fist to enemies directly in front of itself, damaging them. Often raises the amount of damage the user deals.",
		tierlistRank:  "C",
		power:         64,
		cooldown:      5,
	},
	rocksmash:          {
		name:          "Rock Smash",
		type:          "Fighting",
		stoneOptions:  "110000",
		ingameDesc:    "The user unleashes its fury, damaging enemies in a broad area nearby and destroying surrounding trees and rocks.",
		tierlistRank:  "C",
		power:         29,
		cooldown:      1,
	},
	bulkup:             {
		name:          "Bulk Up",
		type:          "Fighting",
		stoneOptions:  "110011",
		ingameDesc:    "The user tenses its muscles to bulk up its body, raising the damage it deals for a while. This also reduces the damage the user takes.",
		tierlistRank:  "S+",
		power:         0,
		cooldown:      8,
	},
	firepunch:          {
		name:          "Fire Punch",
		type:          "Fire",
		stoneOptions:  "111001",
		ingameDesc:    "The user imbues its fist with the power of flames, and strikes enemies directly in front of it with a burning punch. Deals damage and sometimes burns enemies.",
		tierlistRank:  "B",
		power:         229,
		cooldown:      5,
	},
	fireblast:          {
		name:          "Fire Blast",
		type:          "Fire",
		stoneOptions:  "110101",
		ingameDesc:    "The user sprays an all consuming fire on the ground, damaging enemies hit by it and sometimes burning them.",
		tierlistRank:  "B+",
		power:         179,
		cooldown:      5,
	},
	lavaplume:          {
		name:          "Lava Plume",
		type:          "Fire",
		stoneOptions:  "110001",
		ingameDesc:    "The user spouts scarlet flames all around itself. Deals damage to enemies around it. Sometimes burns enemies.",
		tierlistRank:  "C",
		power:         132,
		cooldown:      5,
	},
	heatwave:           {
		name:          "Heat Wave",
		type:          "Fire",
		stoneOptions:  "111101",
		ingameDesc:    "The user exhales hot breath in front of itself, damaging enemies hit by it and sometimes burning them.",
		tierlistRank:  "B-",
		power:         123,
		cooldown:      7,
	},
	ember:              {
		name:          "Ember",
		type:          "Fire",
		stoneOptions:  "110101",
		ingameDesc:    "The user fires sparks in front of itself that split and run in three directions when they hit the ground. Deals damage to enemies they hit. Sometimes burns enemies.",
		tierlistRank:  "C",
		power:         109,
		cooldown:      7,
	},
	firespin:           {
		name:          "Fire Spin",
		type:          "Fire",
		stoneOptions:  "110101",
		ingameDesc:    "The user creates flames all around itself and fires them off in a spiral. Deals damage to enemies they hit. Sometimes burns enemies.",
		tierlistRank:  "B-",
		power:         97,
		cooldown:      5,
	},
	flamethrower:       {
		name:          "Flamethrower",
		type:          "Fire",
		stoneOptions:  "111101",
		ingameDesc:    "The user continuously breathes out long flames for a while. Deals damage to enemies as long as they remain in the flames. Sometimes burns enemies.",
		tierlistRank:  "B-",
		power:         94,
		cooldown:      5,
	},
	flamewheel:         {
		name:          "Flame Wheel",
		type:          "Fire",
		stoneOptions:  "111001",
		ingameDesc:    "The user cloaks itself in fire and charges forward, damaging enemies it hits and sometimes burning them.",
		tierlistRank:  "C",
		power:         57,
		cooldown:      5,
	},
	flamecharge:        {
		name:          "Flame Charge",
		type:          "Fire",
		stoneOptions:  "110011",
		ingameDesc:    "The user stores up the power of flames, raising the damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	flareblitz:         {
		name:          "Flare Blitz",
		type:          "Fire",
		stoneOptions:  "110001",
		ingameDesc:    "The user creates a path of flames in front of itself and charges forward along it. Deals damage to enemies. Sometimes burns enemies.",
		tierlistRank:  "B",
		power:         128,
		cooldown:      5,
	},
	willowisp:          {
		name:          "Will-O-Wisp",
		type:          "Fire",
		stoneOptions:  "111001",
		ingameDesc:    "The user drapes itself with sinister flames and attacks enemies directly in front of it. Often burns enemies.",
		tierlistRank:  "D",
		power:         19,
		cooldown:      3,
	},
	drillpeck:          {
		name:          "Drill Peck",
		type:          "Flying",
		stoneOptions:  "110000",
		ingameDesc:    "The user attacks enemies directly in front of itself with its sharp beak, damaging them.",
		tierlistRank:  "A-",
		power:         321,
		cooldown:      5,
	},
	fly:                {
		name:          "Fly",
		type:          "Flying",
		stoneOptions:  "111000",
		ingameDesc:    "The user flies toward enemies far in front of itself, then swoops down to deal damage to them.",
		tierlistRank:  "B",
		power:         243,
		cooldown:      5,
	},
	bounce:             {
		name:          "Bounce",
		type:          "Flying",
		stoneOptions:  "110000",
		ingameDesc:    "The user bounces forward high into the air twice, damaging enemies it hits.",
		tierlistRank:  "B-",
		power:         186,
		cooldown:      5,
	},
	skyattack:          {
		name:          "Sky Attack",
		type:          "Flying",
		stoneOptions:  "111000",
		ingameDesc:    "After flying up and bracing itself, the user charges at enemies directly in front of itself, damaging them. Critical hits land more easily.",
		tierlistRank:  "B+",
		power:         125,
		cooldown:      5,
	},
	aerialace:          {
		name:          "Aerial Ace",
		type:          "Flying",
		stoneOptions:  "110100",
		ingameDesc:    "The user quickly slashes in front of itself twice, dealing damage.",
		tierlistRank:  "B",
		power:         124,
		cooldown:      5,
	},
	hurricane:          {
		name:          "Hurricane",
		type:          "Flying",
		stoneOptions:  "110101",
		ingameDesc:    "The user whips up an intense wind around itself, damaging surrounding enemies and sometimes confusing them.",
		tierlistRank:  "B-",
		power:         105,
		cooldown:      5,
	},
	gust:               {
		name:          "Gust",
		type:          "Flying",
		stoneOptions:  "111100",
		ingameDesc:    "The user sends an intense gust of wind out in front of itself that whirls around and damages enemies hit by it.",
		tierlistRank:  "C",
		power:         61,
		cooldown:      7,
	},
	tailwind:           {
		name:          "Tailwind",
		type:          "Flying",
		stoneOptions:  "110011",
		ingameDesc:    "The user creates an intense swirling wind that raises its movement speed for a while.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	roost:              {
		name:          "Roost",
		type:          "Flying",
		stoneOptions:  "110000",
		ingameDesc:    "The user briefly rests its body, restoring a bit of its HP.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      9,
	},
	lick:               {
		name:          "Lick",
		type:          "Ghost",
		stoneOptions:  "111001",
		ingameDesc:    "The user licks enemies all around itself with its long tongue, damaging them. Sometimes paralyzes enemies.",
		tierlistRank:  "B",
		power:         233,
		cooldown:      5,
	},
	astonish:           {
		name:          "Astonish",
		type:          "Ghost",
		stoneOptions:  "110000",
		ingameDesc:    "The user tries to startle enemies directly in front of itself, damaging those taken by surprise.",
		tierlistRank:  "B-",
		power:         180,
		cooldown:      5,
	},
	shadowball:         {
		name:          "Shadow Ball",
		type:          "Ghost",
		stoneOptions:  "111101",
		ingameDesc:    "The user hurls a shadowy blob in front of itself, damaging enemies hit by it. Sometimes raises the amount of damage they take.",
		tierlistRank:  "B",
		power:         63,
		cooldown:      7,
	},
	confuseray:         {
		name:          "Confuse Ray",
		type:          "Ghost",
		stoneOptions:  "111101",
		ingameDesc:    "The user exposes surrounding enemies to a sinister ray, often confusing them.",
		tierlistRank:  "B+",
		power:         0,
		cooldown:      3,
	},
	vinewhip:           {
		name:          "Vine Whip",
		type:          "Grass",
		stoneOptions:  "111100",
		ingameDesc:    "The user strikes enemies in front of itself with whiplike vines. Deals damage to enemies hit by them.",
		tierlistRank:  "S+",
		power:         237,
		cooldown:      5,
	},
	solarbeam:          {
		name:          "Solar Beam",
		type:          "Grass",
		stoneOptions:  "111100",
		ingameDesc:    "The user gathers light and unleashes it in front of itself, dealing damage to enemies hit by it.",
		tierlistRank:  "B+",
		power:         227,
		cooldown:      7,
	},
	bulletseed:         {
		name:          "Bullet Seed",
		type:          "Grass",
		stoneOptions:  "111100",
		ingameDesc:    "The user sends several seeds flying out in front of itself simultaneously, damaging enemies hit by them.",
		tierlistRank:  "B",
		power:         168,
		cooldown:      7,
	},
	megadrain:          {
		name:          "Mega Drain",
		type:          "Grass",
		stoneOptions:  "111000",
		ingameDesc:    "The user attacks enemies in front of itself, dealing damage to them. Some of the damage dealt is absorbed by the user, restoring its HP.",
		tierlistRank:  "C",
		power:         165,
		cooldown:      9,
	},
	petaldance:         {
		name:          "Petal Dance",
		type:          "Grass",
		stoneOptions:  "110100",
		ingameDesc:    "The user spins in place, scattering petals that deal damage to enemies around it.",
		tierlistRank:  "C",
		power:         156,
		cooldown:      5,
	},
	razorleaf:          {
		name:          "Razor Leaf",
		type:          "Grass",
		stoneOptions:  "111100",
		ingameDesc:    "The user launches sharp edged leaves to slash at enemies, damaging them. Critical hits land more easily.",
		tierlistRank:  "B-",
		power:         118,
		cooldown:      7,
	},
	leechseed:          {
		name:          "Leech Seed",
		type:          "Grass",
		stoneOptions:  "110100",
		ingameDesc:    "The user plants a seed on the ground in front of itself. Enemies in range are gradually damaged. Part of the damage dealt is absorbed to restore the user's HP.",
		tierlistRank:  "B",
		power:         103,
		cooldown:      9,
	},
	stunspore:          {
		name:          "Stun Spore",
		type:          "Grass",
		stoneOptions:  "111001",
		ingameDesc:    "The user scatters numbing powder directly in front of itself. Often paralyzes enemies hit by it.",
		tierlistRank:  "D",
		power:         21,
		cooldown:      3,
	},
	synthesis:          {
		name:          "Synthesis",
		type:          "Grass",
		stoneOptions:  "110011",
		ingameDesc:    "The user absorbs light, raising the damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	spore:              {
		name:          "Spore",
		type:          "Grass",
		stoneOptions:  "110000",
		ingameDesc:    "The user scatters sleep inducing spores directly in front of itself, often making enemies fall asleep.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      0,
	},
	earthquake:         {
		name:          "Earthquake",
		type:          "Ground",
		stoneOptions:  "110100",
		ingameDesc:    "The user causes an earthquake that damages surrounding enemies.",
		tierlistRank:  "B",
		power:         390,
		cooldown:      5,
	},
	dig:                {
		name:          "Dig",
		type:          "Ground",
		stoneOptions:  "111000",
		ingameDesc:    "The user digs a tunnel to travel beneath the feet of enemies in front of itself, then pops out from beneath them to damage them.",
		tierlistRank:  "B+",
		power:         243,
		cooldown:      5,
	},
	mudbomb:            {
		name:          "Mud Bomb",
		type:          "Ground",
		stoneOptions:  "111101",
		ingameDesc:    "The user throws a lump of mud in front of itself that splits open when it hits the ground, damaging surrounding enemies and sometimes raising the amount of damage they take.",
		tierlistRank:  "B",
		power:         215,
		cooldown:      5,
	},
	bonemerang:         {
		name:          "Bonemerang",
		type:          "Ground",
		stoneOptions:  "111100",
		ingameDesc:    "The user throws a boomerang made of bone, damaging enemies hit by it.",
		tierlistRank:  "B-",
		power:         131,
		cooldown:      7,
	},
	mudslap:            {
		name:          "Mud-Slap",
		type:          "Ground",
		stoneOptions:  "111101",
		ingameDesc:    "The user hurls mud in three directions, dealing damage to enemies hit by it. Sometimes reduces their movement speed.",
		tierlistRank:  "C",
		power:         56,
		cooldown:      7,
	},
	shoreup:            {
		name:          "Shore Up",
		type:          "Ground",
		stoneOptions:  "110000",
		ingameDesc:    "The user gathers sand from beneath itself, restoring a bit of its HP.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      0,
	},
	spikes:             {
		name:          "Spikes",
		type:          "Ground",
		stoneOptions:  "111100",
		ingameDesc:    "The user scatters spikes in front of itself, damaging enemies that step on them.",
		tierlistRank:  "B-",
		power:         221,
		cooldown:      5,
	},
	icepunch:           {
		name:          "Ice Punch",
		type:          "Ice",
		stoneOptions:  "111001",
		ingameDesc:    "The user chills its fist and unleashes a freezing punch on enemies directly in front of it. Sometimes freezes enemies.",
		tierlistRank:  "B-",
		power:         175,
		cooldown:      5,
	},
	iciclecrash:        {
		name:          "Icicle Crash",
		type:          "Ice",
		stoneOptions:  "110101",
		ingameDesc:    "The user drops frigid icicles in front of itself. Deals damage to enemies hit by them and sometimes freezes them.",
		tierlistRank:  "B-",
		power:         143,
		cooldown:      5,
	},
	icebeam:            {
		name:          "Ice Beam",
		type:          "Ice",
		stoneOptions:  "111101",
		ingameDesc:    "The user fires an icy cold beam at enemies in front of itself. Deals damage to enemies and sometimes freezes them.",
		tierlistRank:  "B",
		power:         133,
		cooldown:      7,
	},
	icywind:            {
		name:          "Icy Wind",
		type:          "Ice",
		stoneOptions:  "111101",
		ingameDesc:    "The user sends a freezing gust of chilled air at enemies in front of itself, damaging them. Sometimes lowers enemies' movement speed.",
		tierlistRank:  "B-",
		power:         126,
		cooldown:      7,
	},
	blizzard:           {
		name:          "Blizzard",
		type:          "Ice",
		stoneOptions:  "111001",
		ingameDesc:    "The user moves about while creating a blizzard centered on itself. Deals damage to enemies around the user and sometimes freezes them.",
		tierlistRank:  "D",
		power:         52,
		cooldown:      5,
	},
	auroraveil:         {
		name:          "Aurora Veil",
		type:          "Ice",
		stoneOptions:  "110011",
		ingameDesc:    "The user cloaks itself in a veil of light, reducing the amount of damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      7,
	},
	megapunch:          {
		name:          "Mega Punch",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "After approaching enemies in front of itself, the user slugs enemies directly in front of itself with a muscle packed punch, damaging them.",
		tierlistRank:  "S-",
		power:         561,
		cooldown:      5,
	},
	selfdestruct:       {
		name:          "Self-Destruct",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "The user approaches enemies and causes an explosion, damaging all surrounding enemies. The tradeoff is that the user takes enough damage to knock itself out.",
		tierlistRank:  "B-",
		power:         494,
		cooldown:      5,
	},
	hyperbeam:          {
		name:          "Hyper Beam",
		type:          "Normal",
		stoneOptions:  "111100",
		ingameDesc:    "The user stores up power and then fires a tremendous beam at enemies. Deals severe damage to enemies it hits.",
		tierlistRank:  "A-",
		power:         300,
		cooldown:      10,
	},
	scratch:            {
		name:          "Scratch",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user rakes its hard, pointed claws over enemies directly in front of itself, damaging them.",
		tierlistRank:  "B",
		power:         231,
		cooldown:      5,
	},
	slam:               {
		name:          "Slam",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "The user slams nearby enemies with a long tail, vines, or the like, damaging all of them.",
		tierlistRank:  "B",
		power:         211,
		cooldown:      5,
	},
	takedown:           {
		name:          "Take Down",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user slams into enemies in front of itself with a reckless, full body charge, damaging all enemies hit by it. The user also takes recoil damage.",
		tierlistRank:  "B-",
		power:         189,
		cooldown:      5,
	},
	stomp:              {
		name:          "Stomp",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "The user stomps on enemies in front of itself with a big foot, damaging them.",
		tierlistRank:  "B-",
		power:         180,
		cooldown:      5,
	},
	gigaimpact:         {
		name:          "Giga Impact",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user focuses every bit of its power and charges toward enemies in front of itself, dealing huge damage to them.",
		tierlistRank:  "B-",
		power:         176,
		cooldown:      5,
	},
	tackle:             {
		name:          "Tackle",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user smashes into enemies in front of itself with all its might, damaging them.",
		tierlistRank:  "B-",
		power:         163,
		cooldown:      5,
	},
	furyswipes:         {
		name:          "Fury Swipes",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "The user repeatedly swipes at enemies directly in front of itself, damaging them.",
		tierlistRank:  "A-",
		power:         146,
		cooldown:      5,
	},
	extremespeed:       {
		name:          "Extreme Speed",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user charges into enemies in front of itself with blinding speed, damaging them.",
		tierlistRank:  "B-",
		power:         130,
		cooldown:      5,
	},
	flail:              {
		name:          "Flail",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user flails about, damaging enemies it hits.",
		tierlistRank:  "B-",
		power:         130,
		cooldown:      5,
	},
	triattack:          {
		name:          "Tri Attack",
		type:          "Normal",
		stoneOptions:  "110001",
		ingameDesc:    "The user's body is imbued with three powers as it attacks enemies in front of itself, damaging them. Sometimes burns, paralyzes, or freezes enemies.",
		tierlistRank:  "C",
		power:         81,
		cooldown:      5,
	},
	splash:             {
		name:          "Splash",
		type:          "Normal",
		stoneOptions:  "111100",
		ingameDesc:    "The user splashes in place.",
		tierlistRank:  "D",
		power:         56,
		cooldown:      3,
	},
	harden:             {
		name:          "Harden",
		type:          "Normal",
		stoneOptions:  "110011",
		ingameDesc:    "The user stiffens its body, lowering the damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      5,
	},
	swordsdance:        {
		name:          "Swords Dance",
		type:          "Normal",
		stoneOptions:  "110011",
		ingameDesc:    "With a frenetic dance to uplift the fighting spirit, the user raises the amount of damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	growl:              {
		name:          "Growl",
		type:          "Normal",
		stoneOptions:  "111101",
		ingameDesc:    "The user growls in an endearing way, making surrounding enemies less wary and often reducing the amount of damage they deal.",
		tierlistRank:  "B-",
		power:         0,
		cooldown:      4,
	},
	leer:               {
		name:          "Leer",
		type:          "Normal",
		stoneOptions:  "111001",
		ingameDesc:    "The user glares at nearby enemies to intimidate them, often raising the amount of damage they take.",
		tierlistRank:  "B-",
		power:         0,
		cooldown:      3,
	},
	whirlwind:          {
		name:          "Whirlwind",
		type:          "Normal",
		stoneOptions:  "111100",
		ingameDesc:    "The user whips up a strong wind around itself, blowing away enemies hit by it.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	recover:            {
		name:          "Recover",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "Restoring its own cells, the user restores its HP.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      9,
	},
	roar:               {
		name:          "Roar",
		type:          "Normal",
		stoneOptions:  "110100",
		ingameDesc:    "The user roars intensely, blowing away surrounding enemies.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	softboiled:         {
		name:          "Soft-Boiled",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user restores its HP with the power of eggs.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      9,
	},
	supersonic:         {
		name:          "Supersonic",
		type:          "Normal",
		stoneOptions:  "110101",
		ingameDesc:    "The user generates odd sound waves from its body, often confusing surrounding enemies.",
		tierlistRank:  "B+",
		power:         0,
		cooldown:      3,
	},
	sing:               {
		name:          "Sing",
		type:          "Normal",
		stoneOptions:  "111101",
		ingameDesc:    "The user sings to enemies around itself with its calming voice, often putting them to sleep.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      3,
	},
	transform:          {
		name:          "Transform",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "When Ditto transforms into another Pokemon, this changes into a move that Pokemon can learn.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      0,
	},
	substitute:         {
		name:          "Substitute",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user puts out a substitute for itself that enemies are forced to attack.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	bellydrum:          {
		name:          "Belly Drum",
		type:          "Normal",
		stoneOptions:  "110011",
		ingameDesc:    "The user uses its own HP to raise all of its stats for a while.",
		tierlistRank:  "A-",
		power:         0,
		cooldown:      5,
	},
	workup:             {
		name:          "Work Up",
		type:          "Normal",
		stoneOptions:  "110011",
		ingameDesc:    "The user is roused, raising the amount of damage it deals and reducing the amount of damage it takes for a while.",
		tierlistRank:  "S-",
		power:         0,
		cooldown:      8,
	},
	flash:              {
		name:          "Flash",
		type:          "Normal",
		stoneOptions:  "110001",
		ingameDesc:    "The user suddenly flashes a bright light at surrounding enemies, often lowering their movement speed.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	focusenergy:        {
		name:          "Focus Energy",
		type:          "Normal",
		stoneOptions:  "110011",
		ingameDesc:    "The user takes a deep breath and focuses, raising the amount of damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      5,
	},
	eggbomb:            {
		name:          "Egg Bomb",
		type:          "Normal",
		stoneOptions:  "110100",
		ingameDesc:    "The user scatters eggs around itself, damaging enemies hit by them.",
		tierlistRank:  "B-",
		power:         201,
		cooldown:      5,
	},
	followme:           {
		name:          "Follow Me",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user grabs the attention of surrounding enemies, forcing them to target it.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      2,
	},
	explosion:          {
		name:          "Explosion",
		type:          "Normal",
		stoneOptions:  "111000",
		ingameDesc:    "The user causes a tremendous explosion, dealing huge damage to surrounding enemies. The trade off is that the user takes enough damage to knock itself out.",
		tierlistRank:  "B",
		power:         683,
		cooldown:      5,
	},
	cometpunch:         {
		name:          "Comet Punch",
		type:          "Normal",
		stoneOptions:  "110000",
		ingameDesc:    "The user unleashes a flurry of punches on enemies directly in front of itself, damaging them.",
		tierlistRank:  "B+",
		power:         201,
		cooldown:      5,
	},
	smog:               {
		name:          "Smog",
		type:          "Poison",
		stoneOptions:  "110001",
		ingameDesc:    "The user spews poison around itself, damaging enemies. Sometimes poisons enemies.",
		tierlistRank:  "C",
		power:         188,
		cooldown:      5,
	},
	sludgebomb:         {
		name:          "Sludge Bomb",
		type:          "Poison",
		stoneOptions:  "111101",
		ingameDesc:    "The user shoots out a glob of sludge that splits open when it hits the ground, damaging surrounding enemies. Sometimes poisons enemies.",
		tierlistRank:  "B-",
		power:         173,
		cooldown:      5,
	},
	poisonsting:        {
		name:          "Poison Sting",
		type:          "Poison",
		stoneOptions:  "111001",
		ingameDesc:    "The user fires a poisonous stinger at enemies in front of itself. Sometimes poisons enemies hit by it.",
		tierlistRank:  "B",
		power:         107,
		cooldown:      7,
	},
	poisonpowder:       {
		name:          "Poison Powder",
		type:          "Poison",
		stoneOptions:  "111001",
		ingameDesc:    "The user scatters poison powder in front of itself, often poisoning enemies hit by it.",
		tierlistRank:  "D",
		power:         67,
		cooldown:      4,
	},
	toxic:              {
		name:          "Toxic",
		type:          "Poison",
		stoneOptions:  "111001",
		ingameDesc:    "The user sprays a powerful poison around itself, often poisoning enemies hit by it.",
		tierlistRank:  "D",
		power:         59,
		cooldown:      4,
	},
	acidarmor:          {
		name:          "Acid Armor",
		type:          "Poison",
		stoneOptions:  "110011",
		ingameDesc:    "The user alters its cellular structure to liquefy itself, reducing the damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      5,
	},
	venomdrench:        {
		name:          "Venom Drench",
		type:          "Poison",
		stoneOptions:  "110000",
		ingameDesc:    "The user spews poison in front of itself, sometimes raising the amount of damage enemies take.",
		tierlistRank:  "C",
		power:         118,
		cooldown:      5,
	},
	zenheadbutt:        {
		name:          "Zen Headbutt",
		type:          "Psychic",
		stoneOptions:  "111000",
		ingameDesc:    "The user focuses its willpower to its head, then smashes it into enemies directly in front of itself, dealing damage to enemies hit by it.",
		tierlistRank:  "B-",
		power:         370,
		cooldown:      5,
	},
	psychocut:          {
		name:          "Psycho Cut",
		type:          "Psychic",
		stoneOptions:  "111000",
		ingameDesc:    "After moving forward, the user deals damage to enemies with blades formed by psychic power. Critical hits land more easily.",
		tierlistRank:  "A",
		power:         311,
		cooldown:      5,
	},
	psystrike:          {
		name:          "Psystrike",
		type:          "Psychic",
		stoneOptions:  "111100",
		ingameDesc:    "The user creates a large orb of light in front of itself. The orb then splits into many smaller ones that fly out in all directions, dealing damage to surrounding enemies.",
		tierlistRank:  "C",
		power:         129,
		cooldown:      5,
	},
	psychic:            {
		name:          "Psychic",
		type:          "Psychic",
		stoneOptions:  "110101",
		ingameDesc:    "The user creates a large, mysterious light and fires it out, dealing damage to enemies hit by it. Sometimes raises the amount of damage they take.",
		tierlistRank:  "A",
		power:         121,
		cooldown:      7,
	},
	psybeam:            {
		name:          "Psybeam",
		type:          "Psychic",
		stoneOptions:  "111101",
		ingameDesc:    "The user sends peculiar rays of light out in three directions, damaging enemies hit by them. Sometimes confuses enemies.",
		tierlistRank:  "B-",
		power:         69,
		cooldown:      7,
	},
	barrier:            {
		name:          "Barrier",
		type:          "Psychic",
		stoneOptions:  "110011",
		ingameDesc:    "The user throws up a wall around itself, lowering the amount of damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      5,
	},
	amnesia:            {
		name:          "Amnesia",
		type:          "Psychic",
		stoneOptions:  "110011",
		ingameDesc:    "The user temporarily empties its mind to forget its concerns, raising the amount of damage it deals and making it more resistant to negative effects.",
		tierlistRank:  "A",
		power:         0,
		cooldown:      8,
	},
	lightscreen:        {
		name:          "Light Screen",
		type:          "Psychic",
		stoneOptions:  "110011",
		ingameDesc:    "The user creates a wall of light, making it harder for it to be affected by negative effects for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      3,
	},
	hypnosis:           {
		name:          "Hypnosis",
		type:          "Psychic",
		stoneOptions:  "110000",
		ingameDesc:    "The user employs hypnotic suggestion, often making enemies in front of itself fall asleep.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      0,
	},
	agility:            {
		name:          "Agility",
		type:          "Psychic",
		stoneOptions:  "110011",
		ingameDesc:    "The user relaxes and lightens its body, raising its movement speed for a while.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	teleport:           {
		name:          "Teleport",
		type:          "Psychic",
		stoneOptions:  "110000",
		ingameDesc:    "The user utilizes its psychic powers to teleport. (Meta? for positioning?)",
		tierlistRank:  "C",
		power:         0,
		cooldown:      3,
	},
	meditate:           {
		name:          "Meditate",
		type:          "Psychic",
		stoneOptions:  "110000",
		ingameDesc:    "The user meditates to awaken the power deep within its body, raising the amount of damage it deals for a while.",
		tierlistRank:  "B",
		power:         0,
		cooldown:      0,
	},
	rest:               {
		name:          "Rest",
		type:          "Psychic",
		stoneOptions:  "110000",
		ingameDesc:    "The user rests in place, greatly restoring its HP.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      9,
	},
	rockthrow:          {
		name:          "Rock Throw",
		type:          "Rock",
		stoneOptions:  "110100",
		ingameDesc:    "The user picks up two rocks and hurls them in front of itself, damaging enemies hit by them.",
		tierlistRank:  "S",
		power:         234,
		cooldown:      5,
	},
	rocktomb:           {
		name:          "Rock Tomb",
		type:          "Rock",
		stoneOptions:  "110001",
		ingameDesc:    "The user drops boulders directly in front of itself, damaging enemies hit by them and sometimes lowering their movement speed.",
		tierlistRank:  "B",
		power:         212,
		cooldown:      5,
	},
	stealthrock:        {
		name:          "Stealth Rock",
		type:          "Rock",
		stoneOptions:  "110100",
		ingameDesc:    "The user creates pillars of stone from the ground, damaging enemies hit by them.",
		tierlistRank:  "B",
		power:         120,
		cooldown:      5,
	},
	sandstorm:          {
		name:          "Sandstorm",
		type:          "Rock",
		stoneOptions:  "110000",
		ingameDesc:    "The user creates a sandstorm around itself, damaging enemies hit by it.",
		tierlistRank:  "C",
		power:         117,
		cooldown:      5,
	},
	rollout:            {
		name:          "Rollout",
		type:          "Rock",
		stoneOptions:  "110000",
		ingameDesc:    "The user spins around, damaging surrounding enemies it smashes into.",
		tierlistRank:  "C",
		power:         130,
		cooldown:      5,
	},
	rockpolish:         {
		name:          "Rock Polish",
		type:          "Rock",
		stoneOptions:  "110000",
		ingameDesc:    "The user polishes its body to reduce drag, raising its movement speed for a while.",
		tierlistRank:  "D",
		power:         0,
		cooldown:      2,
	},
	rockblast:          {
		name:          "Rock Blast",
		type:          "Rock",
		stoneOptions:  "110000",
		ingameDesc:    "The user hurls hard rocks in front of itself, damaging enemies hit by them.",
		tierlistRank:  "B-",
		power:         0,
		cooldown:      0,
	},
	metalclaw:          {
		name:          "Metal Claw",
		type:          "Steel",
		stoneOptions:  "111011",
		ingameDesc:    "The user rakes enemies in front of itself with its steel claws, dealing damage. Sometimes raises the amount of damage the user deals.",
		tierlistRank:  "B",
		power:         211,
		cooldown:      5,
	},
	flashcannon:        {
		name:          "Flash Cannon",
		type:          "Steel",
		stoneOptions:  "111101",
		ingameDesc:    "The user focuses all of its light energy into a single point and fires a beam in front of itself, sometimes raising the amount of damage enemies take.",
		tierlistRank:  "B-",
		power:         170,
		cooldown:      7,
	},
	steelwing:          {
		name:          "Steel Wing",
		type:          "Steel",
		stoneOptions:  "111011",
		ingameDesc:    "The user charges at enemies in front of itself and smacks them with its hard wings, dealing damage. Sometimes reduces the amount of damage the user takes.",
		tierlistRank:  "C",
		power:         81,
		cooldown:      5,
	},
	irontail:           {
		name:          "Iron Tail",
		type:          "Steel",
		stoneOptions:  "111001",
		ingameDesc:    "The user swings its steel hard tail, damaging surrounding enemies and sometimes raising the amount of damage they take.",
		tierlistRank:  "C",
		power:         67,
		cooldown:      5,
	},
	metalsound:         {
		name:          "Metal Sound",
		type:          "Steel",
		stoneOptions:  "111101",
		ingameDesc:    "Enemies near the user are forced to listen to a horrible sound like metal scraping, often raising the amount of damage they take.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      3,
	},
	irondefense:        {
		name:          "Iron Defense",
		type:          "Steel",
		stoneOptions:  "110011",
		ingameDesc:    "The user hardens its skin until it's like iron, lowering the damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      5,
	},
	waterfall:          {
		name:          "Waterfall",
		type:          "Water",
		stoneOptions:  "110100",
		ingameDesc:    "The user approaches enemies in front of itself and creates a pillar of water beneath them. This deals damage to enemies it hits.",
		tierlistRank:  "A",
		power:         252,
		cooldown:      5,
	},
	hydropump:          {
		name:          "Hydro Pump",
		type:          "Water",
		stoneOptions:  "111000",
		ingameDesc:    "The user shoots four pillars of water up from the ground and sends them out in front of itself. Deals damage to enemies hit by them.",
		tierlistRank:  "S",
		power:         213,
		cooldown:      5,
	},
	aquajet:            {
		name:          "Aqua Jet",
		type:          "Water",
		stoneOptions:  "110000",
		ingameDesc:    "The user charges at enemies in front of itself with tremendous speed, dealing damage to them.",
		tierlistRank:  "B",
		power:         182,
		cooldown:      5,
	},
	surf:               {
		name:          "Surf",
		type:          "Water",
		stoneOptions:  "111000",
		ingameDesc:    "The user creates a wide wave and charges forward on it. Deals damage to enemies caught in the wave.",
		tierlistRank:  "B",
		power:         127,
		cooldown:      5,
	},
	whirlpool:          {
		name:          "Whirlpool",
		type:          "Water",
		stoneOptions:  "111000",
		ingameDesc:    "The user creates a whirlpool around itself. Deals damage to enemies around the user.",
		tierlistRank:  "C",
		power:         94,
		cooldown:      5,
	},
	bubble:             {
		name:          "Bubble",
		type:          "Water",
		stoneOptions:  "111101",
		ingameDesc:    "The user fires bubbles in three directions. Deals damage to enemies hit by the bubbles and sometimes lowers their movement speed.",
		tierlistRank:  "B-",
		power:         68,
		cooldown:      7,
	},
	withdraw:           {
		name:          "Withdraw",
		type:          "Water",
		stoneOptions:  "110011",
		ingameDesc:    "The user withdraws into its hard shell, reducing the amount of damage it takes for a while.",
		tierlistRank:  "A+",
		power:         0,
		cooldown:      5,
	},
	aquaring:           {
		name:          "Aqua Ring",
		type:          "Water",
		stoneOptions:  "110000",
		ingameDesc:    "The user envelops itself in a veil made of water, restoring some of its HP.",
		tierlistRank:  "C",
		power:         0,
		cooldown:      9,
	},
};
