app.recipeData = {
	ingredients: {
		M: {name: "Rainbow Matter", quality: 2, properties: []},
		R: {name: "Big Root",       quality: 1, properties: ["red",    "soft", "plant"]},
		B: {name: "Icy Rock",       quality: 1, properties: ["blue",   "hard", "mineral"]},
		Y: {name: "Honey",          quality: 1, properties: ["yellow", "soft", "sweet"]},
		G: {name: "Balm Mushroom",  quality: 1, properties: ["gray",   "soft", "mushroom"]},
		S: {name: "Mystical Shell", quality: 1, properties: ["mythical"]},
		r: {name: "Tiny Mushroom",  quality: 0, properties: ["red",    "soft", "mushroom"]},
		b: {name: "Bluk Berry",     quality: 0, properties: ["blue",   "soft", "sweet"]},
		y: {name: "Apricorn",       quality: 0, properties: ["yellow", "hard", "plant"]},
		g: {name: "Fossil",         quality: 0, properties: ["gray",   "hard", "mineral"]},
	},
	dishes: [
		{name: "Red",      properties: {red: 4}},
		{name: "Blue",     properties: {blue: 4}},
		{name: "Yellow",   properties: {yellow: 4}},
		{name: "Gray",     properties: {gray: 4}},
		{name: "Water",    properties: {blue: 3, soft: 4}},
		{name: "Normal",   properties: {gray: 2, sweet: 3}},
		{name: "Poison",   properties: {soft: 3, mushroom: 4}},
		{name: "Ground",   properties: {soft: 3, mineral: 2}},
		{name: "Grass",    properties: {soft: 2, plant: 4}},
		{name: "Bug",      properties: {yellow: 3, sweet: 4}},
		{name: "Psychic",  properties: {hard: 2, sweet: 3}},
		{name: "Rock",     properties: {hard: 4, mineral: 2}},
		{name: "Flying",   properties: {mineral: 3, plant: 2}},
		{name: "Fire",     properties: {red: 1, mushroom: 3}},
		{name: "Electric", properties: {yellow: 3, soft: 4}},
		{name: "Fighting", properties: {sweet: 3, mushroom: 2}},
		{name: "Ambrosia", properties: {mythical: 1}},
		{name: "Mulligan", properties: {}},
	],
	qualityDescriptors: [
		'basic',
		'good',
		'good_nrec',
		'very_good',
		'very_good_nrec',
		'special',
		'special_nrec',
	],
};

app.recipeTable = {
	Red: {
		basic: ['rrrr{bryg}'],
		good: ['{BRYGS}rrrr', 'Rrrr{bryg}'],
		good_nrec: ['R{BRYGS}rrr', 'RRrr{bryg}', 'Mrrrr'],
		very_good: ['RR{BRYGS}rr', 'RRRr{bryg}', 'MRrrr'],
		very_good_nrec: ['RRR{BRYGS}r', 'RRRR{bryg}', 'MRRrr'],
		special: ['RRRR{BRYGS}', 'MRRRr'],
		special_nrec: ['MRRRR'],
	},
	Blue: {
		basic: ['bbbb{bryg}'],
		good: ['{BRYGS}bbbb', 'Bbbb{bryg}'],
		good_nrec: ['B{BRYGS}bbb', 'BBbb{bryg}', 'Mbbbb'],
		very_good: ['BB{BRYGS}bb', 'BBBb{bryg}', 'MBbbb'],
		very_good_nrec: ['BBB{BRYGS}b', 'BBBB{bryg}', 'MBBbb'],
		special: ['BBBB{BRYGS}', 'MBBBb'],
		special_nrec: ['MBBBB'],
	},
	Yellow: {
		basic: ['yyyy{bryg}'],
		good: ['{BRYGS}yyyy', 'Yyyy{bryg}'],
		good_nrec: ['Y{BRYGS}yyy', 'YYyy{bryg}', 'Myyyy'],
		very_good: ['YY{BRYGS}yy', 'YYYy{bryg}', 'MYyyy'],
		very_good_nrec: ['YYY{BRYGS}y', 'YYYY{bryg}', 'MYYyy'],
		special: ['YYYY{BRYGS}', 'MYYYy'],
		special_nrec: ['MYYYY'],
	},
	Gray: {
		basic: ['gggg{bryg}'],
		good: ['{BRYGS}gggg', 'Gggg{bryg}'],
		good_nrec: ['G{BRYGS}ggg', 'GGgg{bryg}', 'Mgggg'],
		very_good: ['GG{BRYGS}gg', 'GGGg{bryg}', 'MGggg'],
		very_good_nrec: ['GGG{BRYGS}g', 'GGGG{bryg}', 'MGGgg'],
		special: ['GGGG{BRYGS}', 'MGGGg'],
		special_nrec: ['MGGGG'],
	},
	Water: {
		basic: ['bbbr{ryg}'],
		good: ['Bbbrr', '{RYGS}bbbr', '{RYG}bbb{ryg}'],
		good_nrec: ['B{RYG}bbr', '{RYGS}{RYG}bbb', 'Mbbbr'],
		very_good: ['B{RYG}{RYG}bb', 'M{RYG}bbb'],
		very_good_nrec: [],
		special: [],
		special_nrec: [],
	},
	Normal: {
		basic: ['bbbgg'],
		good: ['Ybbgg'],
		good_nrec: ['YYbgg', 'YGbbg'],
		very_good: ['YYYgg', 'YYGbg', 'YGGbb'],
		very_good_nrec: ['YYYGg', 'YYGGb'],
		special: ['YYYGG'],
		special_nrec: [],
	},
	Poison: {
		basic: [],
		good: ['Grrr{byg}'],
		good_nrec: ['G{BYGS}rrr', 'GGrr{bryg}'],
		very_good: ['GG{BRYGS}rr', 'GGGr{bry}', 'MGrrr'],
		very_good_nrec: ['GGG{BRYS}r', 'MGGrr'],
		special: ['MGGGr'],
		special_nrec: [],
	},
	Ground: {
		basic: ['rgg{br}{br}'],
		good: ['Brg{br}{br}', '{RYG}rgg{br}', '{RG}gg{br}{br}'],
		good_nrec: ['BBrr{br}', 'B{RYG}g{br}{br}', '{RYG}{RY}rgg', 'R{RYG}gg{br}', 'Y{RG}gg{br}', 'G{RY}gg{br}'],
		very_good: ['BB{RYG}r{br}', 'B{RYG}{RYG}g{br}', 'R{RYG}{RY}gg', 'YY{RG}gg', 'G{RY}{RY}gg'],
		very_good_nrec: ['BB{RYG}{RYG}{br}', 'B{RYG}{RYG}{RY}g'],
		special: ['BB{RYG}{RYG}{RYG}'],
		special_nrec: [],
	},
	Grass: {
		basic: [],
		good: ['Ryyy{br}'],
		good_nrec: ['R{RG}yyy', 'RRyy{bryg}'],
		very_good: ['RR{BRYGS}yy', 'RRRy{byg}'],
		very_good_nrec: ['RRR{BYGS}y', 'MRRyy'],
		special: ['MRRRy'],
		special_nrec: [],
	},
	Bug: {
		basic: [],
		good: ['YYbby'],
		good_nrec: [],
		very_good: ['YYYb{brg}'],
		very_good_nrec: ['YYY{BRGS}b'],
		special: ['MYYYb'],
		special_nrec: [],
	},
	Psychic: {
		basic: ['bbby{yg}'],
		good: ['Ybby{yg}'],
		good_nrec: ['BYbby', 'YYbyg'],
		very_good: ['BYYby'],
		very_good_nrec: [],
		special: [],
		special_nrec: [],
	},
	Rock: {
		basic: ['yygg{bryg}', 'ygg{br}{yg}', 'yggg{bry}'],
		good: ['{BRYGS}yygg', '{BRYS}yggg', 'Byg{bryg}{yg}', 'Bg{br}{yg}{yg}', 'Bggg{bry}', '{RYS}ygg{yg}'],
		good_nrec: ['B{BRYGS}yg{yg}', 'B{BRYS}ggg', 'BB{bryg}{yg}{yg}', 'B{RYS}g{yg}{yg}', 'Mygg{yg}'],
		very_good: ['BB{BRYGS}{yg}{yg}', 'BBB{ryg}{yg}', 'MBg{yg}{yg}'],
		very_good_nrec: ['BBB{RYGS}{yg}', 'MBB{yg}{yg}'],
		special: ['MBBB{yg}'],
		special_nrec: [],
	},
	Flying: {
		basic: [],
		good: ['RRggg'],
		good_nrec: [],
		very_good: ['BRRgg'],
		very_good_nrec: ['BBRRg'],
		special: ['BBBRR'],
		special_nrec: [],
	},
	Fire: {
		basic: ['rrr{byg}{by}'],
		good: ['{BYS}rrr{by}', '{YS}rrr{byg}', 'Grr{byg}{by}'],
		good_nrec: ['{BYS}{YS}rrr', 'G{BRYS}rr{by}', 'G{RYS}rr{byg}', 'GGr{byg}{by}', 'Mrrr{byg}'],
		very_good: ['BG{RYS}rr', 'RG{BYS}rr', 'G{BRYS}{YS}rr', 'GG{BRYS}r{by}', 'GG{RYS}r{byg}', 'M{BYS}rrr', 'MGrr{byg}'],
		very_good_nrec: ['RGGG{by}', 'GG{BRYS}{RYS}r', 'MG{BRYS}rr', 'MGGr{byg}', 'MMrrr'],
		special: ['RGGG{BRYS}', 'MGG{BRYS}r', 'MMGrr'],
		special_nrec: ['MRGGG', 'MMGGr'],
	},
	Electric: {
		basic: [],
		good: ['YYry{br}'],
		good_nrec: [],
		very_good: ['YY{RG}y{br}', 'YYYr{rg}'],
		very_good_nrec: ['RYYY{rg}', 'YY{RG}{RG}y', 'YYY{BRGS}r'],
		special: ['RYYY{BRGS}', 'YYY{BS}{RG}', 'YYYG{BRS}', 'MYYYr'],
		special_nrec: ['MYYY{RG}'],
	},
	Fighting: {
		basic: [],
		good: ['Ybbrr'],
		good_nrec: ['YYbrr', 'YGbbr'],
		very_good: ['YYGbr'],
		very_good_nrec: [],
		special: [],
		special_nrec: [],
	},
	Ambrosia: {
		basic: [],
		good: ['S{bryg}{byg}{br}{yg}', 'Sb{bryg}{bryg}{yg}', 'Sbbr{ryg}', 'Srr{byg}{byg}', 'Syyy{brg}', 'Syyg{bry}'],
		good_nrec: ['S{BRYGS}{br}{yg}{yg}', 'S{BRYGS}b{bryg}{yg}', 'S{BRYGS}bb{ryg}', 'S{BRYGS}r{byg}{byg}', 'S{BRYS}r{bryg}{byg}', 'S{BRY}b{bryg}{ryg}', 'S{BRGS}yyy', 'SB{bryg}{br}{yg}', 'SByy{bry}', 'S{RYGS}yg{bryg}', 'S{RYS}g{bryg}{bryg}', 'S{RGS}yy{bryg}', 'S{RS}y{bryg}{bryg}', 'SR{bryg}{bryg}{yg}', 'SYy{bryg}{brg}', 'SGy{bryg}{byg}', 'SGg{bryg}{by}', 'SGgg{bry}', 'SS{bryg}{bryg}{byg}'],
		very_good: [],
		very_good_nrec: ['S{BRYGSM}{BRYGS}b{yg}', 'S{BRYGSM}{BRYS}r{byg}', 'S{BRYGSM}{RYGS}bb', 'S{BRYGSM}{RYGS}yg', 'S{BRYGSM}{RYS}{bryg}{bg}', 'S{BRYGSM}{RY}y{brg}', 'S{BRYGSM}{GS}yy', 'S{BRYGSbryg}{BRYGS}{RYS}g', 'S{BRYGSbryg}{BRYGS}{RS}b', 'S{BRYGSbryg}{BRYS}{BS}r', 'S{BRYSM}{BYS}rr', 'SB{BRYGSM}{br}{yg}', 'SB{BRYGSM}b{ryg}', 'SB{BRYGSbryg}{RYGS}{byg}', 'SB{BRYGSbryg}{RYS}{bryg}', 'SBB{RYGSbr}{yg}', 'SBB{RYGSryg}b', 'SBB{RYGS}{bryg}', 'SB{RYGSM}bb', 'SB{RYGSM}{yg}{yg}', 'SR{BRYGSbryg}{BRYGS}{bg}', 'SR{BRYGSbryg}{BYGS}y', 'SR{BRYGSbryg}{BYS}{bryg}', 'SR{BYGSM}yy', 'SR{BYSM}rr', 'SRR{BYGSbrg}y', 'SRR{BYGSbyg}r', 'SRR{BYGS}{bryg}', 'SY{BRYGSbryg}{BRGS}{by}', 'SY{BRYGSbryg}{BRS}{bryg}', 'SY{BRGSM}yy', 'SYY{BRGSbryg}{br}', 'SYY{BRGSbrg}y', 'SYY{BRGS}{bryg}', 'SG{BRYGSM}{byg}{by}', 'SG{BRYGSbryg}{BRYS}{byg}', 'SG{BRYSM}r{byg}', 'SG{BRYSM}g{rg}', 'SG{BRYSbyg}{BRYS}r', 'SG{BRYS}{BRYS}{bryg}', 'SGG{BRYGSbyg}{by}', 'SGG{BRYSby}g', 'SS{BRYGSM}{bryg}{byg}', 'SS{BRYGSbryg}{BRYGS}{byg}', 'SS{BRYGSbryg}{BRYS}{bryg}', 'SM{BRYGSbryg}{bryg}{byg}', 'SM{BRYSbyg}rr', 'SM{BRYS}{bryg}{bryg}'],
		special: ['S{BRYGS}{BRYGS}{RYG}{BS}', 'SB{BRYGS}{BRYGS}{RYGS}', 'SRR{BRYGS}{BYGS}', 'SRG{BRYGS}{BRYS}', 'SY{BRYGS}{BRGS}{RG}', 'SGG{BRYGS}{BYS}', 'SS{BRYGS}{BRYGS}{BRYGS}', 'SM{BRYGS}{BRYGS}{byg}', 'SM{BRYGS}{BRYS}{bryg}', 'SMM{bryg}{bryg}'],
		special_nrec: ['SM{BRYGSM}{BRYGS}{BRYGS}', 'SMM{BRYGSMbryg}{BRYGSM}'],
	},
	Mulligan: {
		basic: ['bbrr{yg}', 'bbrg{ry}', 'bby{ryg}{ryg}', 'brrg{by}', 'bry{bryg}{yg}', 'rry{byg}{byg}', 'yyy{brg}{br}', 'yyg{bry}{br}', 'gg{br}{br}{yg}'],
		good: ['{BRYG}bry{byg}', '{BRY}bry{bryg}', '{BRY}rry{byg}', '{BRG}bby{ryg}', '{BG}yyy{br}', 'Byy{bry}{br}', 'Bg{br}{br}{yg}', '{RYG}bbrg', '{RYG}yg{br}{yg}', '{RY}brg{bry}', '{RY}rrg{by}', '{RY}ry{bryg}{bg}', '{RY}ryy{brg}', '{RY}gg{br}{yg}', '{RG}bbg{ry}', '{RG}byg{bryg}', '{RG}yyg{bry}', 'Rbb{ryg}{ry}', 'Rby{bryg}{rg}', 'Rrr{byg}{by}', 'Ryy{brg}{br}', 'Ryg{bryg}{br}', '{YG}bbr{yg}', 'Ybr{br}{yg}', 'Ybyy{rg}', 'Ybyg{ryg}', 'Yg{br}{yg}{yg}', 'Gbrg{by}', 'Gby{bryg}{yg}', 'Gry{byg}{byg}', 'Gyyy{brg}'],
		good_nrec: ['{BRYG}{BR}bry', '{BRYG}{RY}ryg', '{BRYG}{RG}by{bg}', '{BY}{RG}by{bryg}', 'B{BRY}rry', 'BBr{br}{yg}', 'B{RYG}{br}{yg}{yg}', 'B{RY}br{ry}', 'B{RY}rr{by}', 'B{RY}ry{bryg}', 'B{RG}yy{bry}', 'BRy{bryg}{br}', '{RYG}{RY}brg', '{RYG}{RY}ygg', 'R{BRYG}by{brg}', 'R{BRYG}ry{bg}', 'R{BRYG}yg{br}', 'R{BYG}by{bryg}', 'R{BYG}yy{br}', 'R{BY}rr{by}', 'R{BY}ry{bryg}', 'R{RYG}bb{ryg}', 'R{RYG}br{bg}', 'R{RYG}bg{bry}', 'R{RG}br{byg}', 'R{RG}rg{by}', 'RRy{brg}{bg}', 'R{YG}yy{brg}', 'R{YG}yg{bryg}', 'RYb{bryg}{ry}', 'RYr{bryg}{by}', 'RYrr{byg}', 'RYy{bryg}{brg}', 'RYg{bry}{br}', 'RGr{byg}{by}', 'Y{BRG}by{ryg}', 'Y{BRG}ry{by}', 'Y{BRG}yy{br}', 'Y{BR}rr{by}', 'Y{BR}ry{bryg}', 'Y{RY}bb{rg}', 'Y{RY}rg{bry}', 'Y{RY}gg{yg}', 'Y{RG}y{bryg}{bg}', 'Y{RG}yy{brg}', 'YYbr{bg}', 'YYbg{br}', 'YYyg{rg}', 'YGbr{yg}', 'YGbg{ry}', 'G{BRYG}by{byg}', 'G{BRY}by{bryg}', 'G{BRY}ry{byg}', 'G{BG}yyy', 'G{RYG}yyg', 'G{RY}rg{by}', 'G{RY}y{bryg}{bg}', 'G{RY}yy{brg}', 'G{RG}bbg', 'GGbb{yg}', 'GGy{byg}{by}', 'GGg{by}{by}', 'M{bryg}{byg}{br}{yg}', 'Mb{bryg}{bryg}{yg}', 'Mbbr{ryg}', 'Mrr{byg}{byg}', 'Myyy{brg}', 'Myyg{bry}'],
		very_good: ['B{BRYG}{RY}ry', 'B{BRYG}{RG}by', 'BBBrr', 'BB{RYG}{br}{yg}', 'B{RYG}{RYG}yg', 'B{RYG}{RY}br', 'BR{BRYG}y{br}', 'BR{RYG}b{ry}', 'BR{RG}r{by}', 'BR{YG}y{bryg}', 'BR{YG}g{yg}', 'BY{RYG}g{yg}', 'BY{RY}r{bry}', 'BY{RG}b{ry}', 'BY{RG}y{bryg}', 'BYYy{rg}', 'BG{RYG}y{yg}', 'BG{RY}b{ry}', 'BG{RY}r{by}', 'BG{RY}y{bryg}', 'BG{RY}g{yg}', 'R{BRYG}{BG}by', 'R{BRYG}{YG}yg', 'R{RYG}{RYG}b{bg}', 'RR{BYG}b{ry}', 'RR{BYG}r{by}', 'RR{BYG}y{brg}', 'RR{YG}b{bryg}', 'RR{YG}r{byg}', 'RR{YG}g{bry}', 'RY{BRYG}br', 'RY{BRG}y{br}', 'RY{BY}rr', 'RY{BG}y{bryg}', 'RY{RYG}g{bry}', 'RY{RG}b{bryg}', 'RY{RG}r{byg}', 'RYY{brg}{br}', 'RYG{bryg}{by}', 'RG{BRYG}y{bg}', 'RG{BRY}r{by}', 'RG{BYG}yy', 'RG{BY}y{bryg}', 'RG{RY}b{bryg}', 'RG{RY}r{byg}', 'RG{RY}g{bry}', 'RGG{byg}{by}', 'Y{BRYG}{RG}yg', 'Y{BRG}{BRG}by', 'Y{BR}{YG}br', 'YY{BRG}yg', 'YY{BR}r{br}', 'YY{RG}bb', 'YY{RG}rg', 'YYGg{ry}', 'YG{BRG}y{by}', 'YG{BR}r{by}', 'YG{BR}y{bryg}', 'YG{RY}bb', 'YG{RG}bg', 'YGGb{yg}', 'G{BRYG}{BRG}by', 'G{BRYG}{RY}yg', 'G{BRY}{BR}ry', 'G{RY}{RY}rg', 'GG{BRYG}y{by}', 'GG{BRY}y{byg}', 'GG{RY}g{by}', 'GG{RG}bb', 'GGG{by}{by}', 'M{BRYG}{br}{yg}{yg}', 'M{BRYG}b{bryg}{yg}', 'M{BRYG}bb{ryg}', 'M{BRYG}r{byg}{byg}', 'M{BRY}b{bryg}{ryg}', 'M{BRY}r{bryg}{byg}', 'M{BRG}yyy', 'MB{bryg}{br}{yg}', 'MByy{bry}', 'M{RYG}yg{bryg}', 'M{RY}g{bryg}{bryg}', 'M{RG}yy{bryg}', 'MR{bryg}{bryg}{yg}', 'MYy{bryg}{brg}', 'MGy{bryg}{byg}', 'MGg{bryg}{by}', 'MGgg{bry}'],
		very_good_nrec: ['BBB{RYG}r', 'BB{RYG}{RYG}y', 'BB{RYG}{YG}{yg}', 'B{RYG}{RYG}{RG}b', 'BR{BRYG}{YG}y', 'BRR{YG}{bry}', 'BRY{RYG}{bry}', 'BY{BRYG}{RG}y', 'BYY{BRG}y', 'BYY{RG}{bry}', 'BG{BRYG}{RYG}y', 'BG{RY}{RY}{bry}', 'BGG{RYG}{by}', 'RR{BRYG}{YG}b', 'RR{BYG}{BG}y', 'RR{RYG}{YG}g', 'RRR{BYG}b', 'RRR{YG}{bg}', 'RRY{BYG}r', 'RRYG{bryg}', 'RRG{BY}r', 'RY{BRYG}{RG}b', 'RY{RYG}{RG}g', 'RYY{BRG}{br}', 'RYY{RG}{brg}', 'RYG{BRY}r', 'RG{BRYG}{RY}b', 'RG{RYG}{RY}g', 'RGG{BRY}{by}', 'RGG{RY}{byg}', 'YY{RG}{RG}g', 'YYG{BR}{br}', 'YG{BRG}{RG}y', 'YGG{BRG}{by}', 'GG{RY}{RY}g', 'GGG{BY}{by}', 'M{BRYG}{BRYG}b{yg}', 'M{BRYG}{BRY}r{byg}', 'M{BRYG}{RYG}bb', 'M{BRYG}{RYG}yg', 'M{BRYG}{RY}{bryg}{bg}', 'M{BRYG}{RY}y{brg}', 'M{BRY}{BY}r{bryg}', 'MB{BRYG}{br}{yg}', 'MB{BRYG}b{ryg}', 'MB{RYG}{bryg}{byg}', 'MB{RYG}{yg}{yg}', 'MB{RY}{bryg}{bryg}', 'MR{BYG}y{bryg}', 'MR{BY}{bryg}{bryg}', 'MY{BRG}y{bryg}', 'MY{BR}{bryg}{bryg}', 'MYY{bryg}{brg}', 'MG{BRYG}{byg}{by}', 'MG{BRY}{bryg}{byg}', 'MM{bryg}{bryg}{byg}'],
		special: ['BBB{RYG}{YG}', 'BRR{RYG}{YG}', 'BRG{RYG}{RY}', 'BY{RYG}{RG}{RG}', 'RRR{BYG}{YG}', 'RRYG{BRYG}', 'RGG{BRY}{RY}', 'YY{BRG}{RG}{RG}', 'YGGG{BY}', 'M{BRYG}{BRYG}{RY}g', 'M{BRYG}{BRYG}{RG}b', 'MB{BRYG}{BRY}r', 'MB{BRYG}{RYG}{byg}', 'MB{BRYG}{RY}{bryg}', 'MBB{RYG}{bryg}', 'MR{BRYG}{BRYG}{bg}', 'MR{BRYG}{BYG}y', 'MR{BRYG}{BY}{bryg}', 'MRR{BYG}{bryg}', 'MY{BRYG}{BRG}{by}', 'MY{BRYG}{BR}{bryg}', 'MYY{BRG}{bryg}', 'MG{BRYG}{BRYG}{by}', 'MG{BRYG}{BRY}{byg}', 'MG{BRY}{BRY}{bryg}', 'MM{BRYG}{bryg}{byg}', 'MM{BRY}{bryg}{bryg}'],
		special_nrec: ['MB{BRYGM}{BRYG}{RYG}', 'MBBB{RYGM}', 'MRR{BRYGM}{BYG}', 'MRRR{BYGM}', 'MRG{BRYGM}{BRY}', 'MRGG{BRYM}', 'MY{BRYGM}{BRG}{RG}', 'MYY{BRGM}{RG}', 'MYYY{BM}', 'MGG{BRYGM}{BY}', 'MGGG{BYM}', 'MM{BRYGMbryg}{BRYGM}{BRY}', 'MM{BRYGM}{BRYG}{byg}', 'MMG{BRYGMbryg}{BRYM}', 'MMGG{BRYGMbyg}', 'MMM{BRYGMbryg}{BRYGMbryg}'],
	},
};

app.recipeWeightSums = {
	Red: {
		basic:         70000,
		good:          61335,
		very_good:     86700,
		special:       26700,
	},
	Blue: {
		basic:         50000,
		good:          51280,
		very_good:     75600,
		special:       25600,
	},
	Yellow: {
		basic:         80000,
		good:          11840,
		very_good:     46800,
		special:       36800,
	},
	Gray: {
		basic:         40000,
		good:          81010,
		very_good:     100200,
		special:       20200,
	},
	Water: {
		basic:         60000,
		good:          40775,
		very_good:     55500,
		special:       15500,
	},
	Normal: {
		basic:         40000,
		good:          40770,
		very_good:     55400,
		special:       15400,
	},
	Poison: {
		basic:         60000,
		good:          40775,
		very_good:     55500,
		special:       15500,
	},
	Ground: {
		basic:         30000,
		good:          20500,
		very_good:     30000,
		special:       10000,
	},
	Grass: {
		basic:         20000,
		good:          20500,
		very_good:     30000,
		special:       10000,
	},
	Bug: {
		basic:         20000,
		good:          10370,
		very_good:     17400,
		special:       7400,
	},
	Psychic: {
		basic:         10000,
		good:          20500,
		very_good:     30000,
		special:       10000,
	},
	Rock: {
		basic:         20000,
		good:          10275,
		very_good:     15500,
		special:       5500,
	},
	Flying: {
		basic:         20000,
		good:          20310,
		very_good:     26200,
		special:       6200,
	},
	Fire: {
		basic:         20000,
		good:          10500,
		very_good:     20000,
		special:       10000,
	},
	Electric: {
		basic:         10000,
		good:          10500,
		very_good:     20000,
		special:       10000,
	},
	Fighting: {
		basic:         10000,
		good:          10400,
		very_good:     18000,
		special:       8000,
	},
	Ambrosia: {
		basic:         300,
		good:          300,
		very_good:     300,
		special:       630,
	},
	Mulligan: {
		basic:         240000,
		good:          215000,
		very_good:     500000,
		special:       300000,
	},
};